[package]
name = "infuse"
version = "0.1.0"
edition = "2018"
authors = ["Sébastien Lerique <sl@mehho.net>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.42"
lopdf = "0.20"
xml-rs = "0.8"
console_error_panic_hook = "0.1.6"
log = "0.4"
env_logger = "0.6"
